#!/bin/bash

#SBATCH --job-name=inference_unsloth
#SBATCH --partition=gpu_h100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=2
#SBATCH --time=2:00:00

# Activate your Python virtual environment
source venv/bin/activate

# Set HuggingFace cache location
export HF_HOME=/scratch-shared/$USER/.cache_dir/
#  --model_name ./finetuned_model_mask/lora_final \
#   --model_name unsloth/Qwen3-14b \
 # --input_jsonl raw_test_sorted_100.jsonl \
 # --output_jsonl test_coordinates_results.jsonl \
python inferencestep.py \
  --model_name unsloth/Qwen3-32b \
  --input_jsonl test_input_100.jsonl \
  --output_jsonl aresults_singleshot_step_32b.jsonl \
  --masking_counts 1 3 5 \
  --batch_size 1 \
  --max_seq_length 16000 \
  --load_in_4bit False \
  --finetune False \
  --mode singleshot \
  --include_masked_holes True\
  --output_format hole_and_lengths
